### ISSUE TITLE
Open Food Facts et pas OpenFoodFacts

### ISSUE THREAD

**Issue by CharlesNepote** [FredJul/verdure#1]
Bravo pour l'app au passage ! (Très épurée, joliment designée, simple et efficace.)

Open Food Facts s'écrit avec des espaces et non tout attaché, si vous pouvez corriger à l'occasion (rien d'urgent ni de dramatique) ?

**Comment by FredJul** [comment]
Merci pour le compliment et pour l'info, je changement ça pour la prochaine version !
